name: "2.2"
on:
  push:

jobs:
  first-job: 

    runs-on: ubuntu-latest
    steps: 
      - name: "hello world"
        run: echo "ecole-it"

  second-job: 

    runs-on: ubuntu-latest
    steps: 
      - name: "hello world"
        run: echo "ecole-it"

  last-job: 

    runs-on: ubuntu-latest
    steps: 
      - name: "hello world"
        run: echo "ecole-it"
